### PR TITLE
Added capability to set a custom container

### PR DESCRIPTION
**Pull request by gertsonderby**
API chosen based on [`react-testing-library#render`](https://testing-library.com/docs/react-testing-library/api#render-options).

### CODE REVIEW

**Comment by sunesimonsen** [comment]
It would be nice also to support just using a string for the container.

**Comment by sunesimonsen** [comment]
But I can add that if you just want this merged. Then we can do that.

**Comment by gertsonderby** [comment]
Would we want a separate option for the string (if we're leaning on the rtl API)? Like `{ containerType: 'tr' }` for example.

**Comment by alexjeffburke** [comment]
I think when this came up on the channel there was a consensus we’d call the option “tagName” to be compatible with the DOM? :)

**Comment by gertsonderby** [comment]
Good choice.

**Comment by gertsonderby** [comment]
... We could just overload `container`... Would that be naughty?

**Comment by gertsonderby** [comment]
Built the tagName version, renaming it would be trivial, let me know.

**Comment by sunesimonsen** [comment]
@gertsonderby and @alexjeffburke I'm sorry, but I would much prefer that we overload the container option to also accept strings. Having options that disable other options doesn't feel too great.

**Comment by gertsonderby** [comment]
I'll have that set up in a jiffy, boss.

**Comment by sunesimonsen** [comment]
Thanks! released as react-dom-testing@1.11.0

**Pull request merged**
